# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

name = "hono-compute-ws"
authors = [""]
description = "Example for using serve-grip with WebSockets-over-HTTP in Hono running on Fastly Compute"
language = "javascript"
manifest_version = 3
service_id = ""

[local_server.pushpin]
  enable = true

[local_server.backends]
  [local_server.backends.self]
    url = "http://localhost:7676/"
    override_host = "localhost:7676"

[local_server.config_stores]
  [local_server.config_stores.grip]
    format = "inline-toml"
  [local_server.config_stores.grip.contents]
    GRIP_URL = "http://localhost:5561/"

[scripts]
  build = "npm run build"
  post_init = "npm install"
